### Send POST request with json body
POST http://localhost:8080/hsm
Content-Type: application/json

{
  "Header":{
    "funcNm": "ExampleService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref" : "th"
  }
}

###
