### Send POST request with json body
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header":{
    "funcNm": "AirQualityService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref" : "th"
  }
}

###
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header": {
    "funcNm": "HsmService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref": "th"
  }
}

###
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header": {
    "funcNm": "KPeopleService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref": "th"
  },
  "Body": {
    "EMP_ID": "965150",
    "CO_TP_CD": "KSOFT"
  }
}
###
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header": {
    "funcNm": "DopaService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref": "th"
  },
  "Body": {
    "nid": "4150450100248",
    "first_name": "สมชาย",
    "middle_name": "",
    "last_name": "สัญญา",
    "birth_date": "25270127",
    "laser_id": "EE0112564917"
  }
}

###
