### Send POST request with json body
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header":{
    "funcNm": "AirQualityService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref" : "th"
  }
}

###
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header": {
    "funcNm": "HsmService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref": "th"
  }
}

###
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header": {
    "funcNm": "KPeopleService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref": "th"
  },
  "Body": {
    "EMP_ID": "965150",
    "CO_TP_CD": "KSOFT"
  }
}
###
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header": {
    "funcNm": "DopaService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref": "th"
  },
  "Body": {
    "nid": "3450394857362",
    "first_name": "aaaaa",
    "middle_name": "",
    "last_name": "bbbbb",
    "birth_date": "25251127",
    "laser_id": "EEXXXXXXX"
  }
}

###
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header": {
    "funcNm": "MailService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref": "th"
  }
}

###
POST http://localhost:8080/api
Content-Type: application/json

{
  "Header": {
    "funcNm": "QRService",
    "rqUID": "",
    "rqDt": "",
    "rqAppId": "123",
    "userLangPref": "th"
  },
  "Body": {
    "input": "3450394857362"
  }
}

###