package http

import "fmt"

/*type ReqHeader struct {
	FuncNm       string `json:"funcNm"`
	RqUID        string `json:"rqUID"`
	RqDt         string `json:"rqDt"`
	RqAppID      string `json:"rqAppId"`
	UserLangPref string `json:"userLangPref"`
}

type ResHeader struct {
	FuncNm     string     `json:"funcNm"`
	RqUID      string     `json:"rqUID"`
	RsAppID    string     `json:"rsAppId"`
	RsUID      string     `json:"rsUID"`
	RsDt       time.Time  `json:"rsDt"`
	StatusCode string     `json:"statusCode"`
	ErrorVect  *ErrorVect `json:"errorVect,omitempty"`
}

type ErrorVect struct {
	Error []Error `json:"error"`
}

type Error struct {
	ErrorAppID    string `json:"errorAppId"`
	ErrorAppAbbrv string `json:"errorAppAbbrv"`
	ErrorCode     string `json:"errorCode"`
	ErrorDesc     string `json:"errorDesc"`
	ErrorSeverity string `json:"errorSeverity"`
}

type ReqMsg struct {
	Header ReqHeader   `json:"Header"`
	Body   interface{} `json:"Body"`
}

type ResMsg struct {
	Header ResHeader   `json:"Header"`
	Body   interface{} `json:"Body,omitempty"`
}*/

type AutoGenerated []struct {
	Name        string `json:"name"`
	ID          string `json:"id"`
	Aqi         int    `json:"aqi"`
	Type        string `json:"type"`
	Coordinates struct {
		Latitude  float64 `json:"latitude"`
		Longitude float64 `json:"longitude"`
	} `json:"coordinates"`
}
type KPeopleReq struct {
	EMPID  string `json:"EMP_ID"`
	COTPCD string `json:"CO_TP_CD"`
}

func (k *KPeopleReq) String() string {
	return fmt.Sprintf("EMP_ID=%s&CO_TP_CD=%s", k.EMPID, k.COTPCD)
}

type KPeopleRes struct {
	EMPID           string      `json:"EMP_ID"`
	THTTL           string      `json:"TH_TTL"`
	THFRSTNM        string      `json:"TH_FRST_NM"`
	THSURNM         string      `json:"TH_SUR_NM"`
	ENTTL           string      `json:"EN_TTL"`
	ENFRSTNM        string      `json:"EN_FRST_NM"`
	ENSURNM         string      `json:"EN_SUR_NM"`
	BRTHDT          interface{} `json:"BRTH_DT"`
	IDENTNO         interface{} `json:"IDENT_NO"`
	EMPDT           string      `json:"EMP_DT"`
	EMPEPDT         string      `json:"EMP_EP_DT"`
	EMPTPCD         string      `json:"EMP_TP_CD"`
	EMPTPDSC        string      `json:"EMP_TP_DSC"`
	EMPCTRTPCD      string      `json:"EMP_CTR_TP_CD"`
	EMPLCSTPCD      string      `json:"EMP_LCS_TP_CD"`
	EMPSTCD         string      `json:"EMP_ST_CD"`
	DEPTID          string      `json:"DEPT_ID"`
	THDEPTNM        string      `json:"TH_DEPT_NM"`
	ENDEPTNM        string      `json:"EN_DEPT_NM"`
	BSNLINEDEPTID   string      `json:"BSN_LINE_DEPT_ID"`
	THBSNLINEDEPTNM string      `json:"TH_BSN_LINE_DEPT_NM"`
	ENBSNLINEDEPTNM string      `json:"EN_BSN_LINE_DEPT_NM"`
	PRNDEPTID       string      `json:"PRN_DEPT_ID"`
	THPRNDEPTNM     string      `json:"TH_PRN_DEPT_NM"`
	THPRNDEPTABR    string      `json:"TH_PRN_DEPT_ABR"`
	ENPRNDEPTNM     string      `json:"EN_PRN_DEPT_NM"`
	ENPRNDEPTABR    string      `json:"EN_PRN_DEPT_ABR"`
	RGONCD          int         `json:"RGON_CD"`
	ZONCD           int         `json:"ZON_CD"`
	JOBCD           string      `json:"JOB_CD"`
	THJOBNM         string      `json:"TH_JOB_NM"`
	ENJOBNM         string      `json:"EN_JOB_NM"`
	CORPTTLCD       string      `json:"CORP_TTL_CD"`
	THCORPTTLNM     interface{} `json:"TH_CORP_TTL_NM"`
	ENCORPTTLNM     interface{} `json:"EN_CORP_TTL_NM"`
	KBNKAREANO      string      `json:"KBNK_AREA_NO"`
	NTWCNTRCD       string      `json:"NTW_CNTR_CD"`
	DEPTCNTRCD      string      `json:"DEPT_CNTR_CD"`
	UNITCNTRCD      string      `json:"UNIT_CNTR_CD"`
	SUBUNITCNTRCD   string      `json:"SUB_UNIT_CNTR_CD"`
	KBNKBRNO        string      `json:"KBNK_BR_NO"`
	CNTRTPCD        string      `json:"CNTR_TP_CD"`
	EMPOFCRTPCD     string      `json:"EMP_OFCR_TP_CD"`
	EMAILADR        string      `json:"EMAIL_ADR"`
	OFFCPH1         string      `json:"OFFC_PH1"`
	OFFCPH1EXT      string      `json:"OFFC_PH1_EXT"`
	OFFCPH2         string      `json:"OFFC_PH2"`
	OFFCPH2EXT      string      `json:"OFFC_PH2_EXT"`
	OFFCPH3         string      `json:"OFFC_PH3"`
	OFFCPH3EXT      string      `json:"OFFC_PH3_EXT"`
	FAX             string      `json:"FAX"`
	FAXEXT          string      `json:"FAX_EXT"`
	MBLPH1          string      `json:"MBL_PH1"`
	MBLPH2          string      `json:"MBL_PH2"`
	TMTDT           interface{} `json:"TMT_DT"`
	GNDCD           string      `json:"GND_CD"`
	ETHNCGRP        string      `json:"ETHNC_GRP"`
	COTPCD          string      `json:"CO_TP_CD"`
	COTPNM          string      `json:"CO_TP_NM"`
	COTPCAT         string      `json:"CO_TP_CAT"`
	COLOGOSPPATH    string      `json:"CO_LOGO_SP_PATH"`
	SPVSRID         string      `json:"SPVSR_ID"`
	MONKF           string      `json:"MONK_F"`
	PROVCD          string      `json:"PROV_CD"`
	DEPTCD          string      `json:"DEPT_CD"`
	PRBTDT          string      `json:"PRBT_DT"`
	PRBTF           string      `json:"PRBT_F"`
	DSCLNF          string      `json:"DSCLN_F"`
	CLMF            string      `json:"CLM_F"`
	PNDGDOCF        string      `json:"PNDG_DOC_F"`
	QUALFDSC        string      `json:"QUALF_DSC"`
	PPNTMS          string      `json:"PPN_TMS"`
	SRCSTMID        int         `json:"SRC_STM_ID"`
	IsUser          bool        `json:"IsUser"`
	EMPBuilding     string      `json:"EMP_Building"`
	EMPSecretary    interface{} `json:"EMP_Secretary"`
	EMPSecretaryTEL interface{} `json:"EMP_Secretary_TEL"`
	EMPCoverImage   string      `json:"EMP_CoverImage"`
	EMPAchievement  interface{} `json:"EMP_Achievement"`
	EMPExperties    interface{} `json:"EMP_Experties"`
	EMPLineID       string      `json:"EMP_LineID"`
	EMPNicknameTH   string      `json:"EMP_Nickname_TH"`
	EMPNicknameEN   string      `json:"EMP_Nickname_EN"`
	EMPOFFCPH1      string      `json:"EMP_OFFC_PH1"`
	EMPOFFCPH2      interface{} `json:"EMP_OFFC_PH2"`
	EMPMBLPH1       string      `json:"EMP_MBL_PH1"`
	EMPMBLPH2       interface{} `json:"EMP_MBL_PH2"`
	EMPOFFCFAX      interface{} `json:"EMP_OFFC_FAX"`
	EMPInterests    interface{} `json:"EMP_Interests"`
	COMPNAME        interface{} `json:"COMPNAME"`
	JOBLAYER        string      `json:"JOB_LAYER"`
	ENCNTRNMABR     interface{} `json:"EN_CNTR_NM_ABR"`
	COLOGO          string      `json:"CO_LOGO"`
}
