package http

import (
	"encoding/json"
	"net/http"
)

func (s *Client) CheckStatus() (*AutoGenerated, error) {
	//url := fmt.Sprintf(baseURL)
	req, err := http.NewRequest("GET", baseURL, nil)
	if err != nil {
		return nil, err
	}
	bytes, err := s.doRequest(req)
	if err != nil {
		return nil, err
	}
	var data AutoGenerated
	err = json.Unmarshal(bytes, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}
