package service

//
//type IAQIService interface {
//	HSMStatus(ReqMsg) ResMsg
//}
//
//type AQIService struct {
//	IServiceTemplate
//	Request  ReqMsg
//	Response ResMsg
//	http.IHTTPService
//	backendResp *http.AutoGenerated
//}
//
//func (s *AQIService) getResponse() ResMsg {
//	return s.Response
//}
//
//func (s *AQIService) setRequest(r ReqMsg) error {
//	s.Request = r
//	return nil
//}
//
//func (s *AQIService) Validate() error {
//	return nil
//}
//
//func (s *AQIService) OutputMapping() error {
//	s.Response = ResMsg{
//		Header: ResHeader{},
//		Body:   s.backendResp,
//	}
//	return nil
//}
//
//func (s *AQIService) InputMapping() error {
//	return nil
//}
//
//func (s *AQIService) Business() error {
//
//	r, err := s.IHTTPService.CheckStatus()
//	s.backendResp = r
//	if err != nil {
//		return err
//	}
//	return nil
//}
//
//func (s *AQIService) HSMStatus(req ReqMsg) ResMsg {
//
//	r, _ := DoService(req, s)
//	//if err != nil {
//	//	return "Doservice Error"
//	//}
//	return r
//}
//
