package service

import (
	"github.com/pruknil/goapp/backends/http"
	"github.com/pruknil/goapp/backends/socket/hsm"
)

type ExampleService struct {
	baseService
	http.IHTTPService
	hsm.IHSMService
	backendResp *http.AutoGenerated
}

func (s *ExampleService) OutputMapping() error {
	s.Response = ResMsg{
		Header: ResHeader{},
		Body:   s.backendResp,
	}
	return nil
}

func (s *ExampleService) InputMapping() error {
	return nil
}

func (s *ExampleService) Business() error {
	x, err := s.IHTTPService.CheckStatus()
	s.backendResp = x
	if err != nil {
		return err
	}
	return nil
}

type HsmService struct {
	baseService
	hsm.IHSMService
	backendResp *hsm.StatusResponse
}

func (s *HsmService) OutputMapping() error {
	s.Response = ResMsg{
		Header: ResHeader{},
		Body:   s.backendResp,
	}
	return nil
}

func (s *HsmService) InputMapping() error {
	return nil
}

func (s *HsmService) Business() error {
	x, err := s.IHSMService.CheckStatus()
	if err != nil {
		return err
	}
	s.backendResp = x
	return nil
}
