package service

import (
	"encoding/json"
	"github.com/pruknil/goapp/backends/http"
	"github.com/pruknil/goapp/backends/socket/hsm"
)

type ExampleService struct {
	baseService
	http.IHTTPService
	hsm.IHSMService
	backendResp *http.AutoGenerated
}

func (s *ExampleService) OutputMapping() error {
	s.Response = ResMsg{
		Header: ResHeader{},
		Body:   s.backendResp,
	}
	return nil
}

func (s *ExampleService) InputMapping() error {
	return nil
}

func (s *ExampleService) Business() error {
	x, err := s.IHTTPService.CheckStatus()
	s.backendResp = x
	if err != nil {
		return err
	}
	return nil
}

type HsmService struct {
	baseService
	hsm.IHSMService
	backendResp *hsm.StatusResponse
}

func (s *HsmService) OutputMapping() error {
	s.Response = ResMsg{
		Header: ResHeader{},
		Body:   s.backendResp,
	}
	return nil
}

func (s *HsmService) InputMapping() error {
	return nil
}

func (s *HsmService) Business() error {
	x, err := s.IHSMService.CheckStatus()
	if err != nil {
		return err
	}
	s.backendResp = x
	return nil
}

type KPeopleService struct {
	baseService
	http.IHTTPService
	backendResp *http.KPeopleRes
}

func (s *KPeopleService) OutputMapping() error {
	s.Response = ResMsg{
		Header: ResHeader{},
		Body:   s.backendResp,
	}
	return nil
}

func (s *KPeopleService) InputMapping() error {
	return nil
}

func (s *KPeopleService) Business() error {
	peopleReq := http.KPeopleReq{}
	jsonString, _ := json.Marshal(s.Request.Body)
	json.Unmarshal(jsonString, &peopleReq)
	res, err := s.IHTTPService.KPeopleGetData(peopleReq)
	s.backendResp = res
	if err != nil {
		return err
	}
	return nil
}
